default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: friendlink_app_development
test:
  <<: *default
  database: friendlink_app_test

production:
  <<: *default
  database: friendlink_app_production
  username: friendlink_app
  password: <%= ENV['FRIENDLINK_APP_DATABASE_PASSWORD'] %>
